### PayPal
# curl -X POST http://localhost:8081/api/paypal/transaction
#-H "Content-Type: application/json"
#-d '{
#    "amount": 1000,
#    "currency": "USD",
#    "description": "Test transaction"
#}'
POST http://localhost:9011/api/paypal/transaction
Content-Type: application/json

{
  "amount": 1000,
  "currency": "USD",
  "description": "Test transaction"
}

### Stripe
# curl -X POST http://localhost:8081/api/stripe/charge
#-H "Content-Type: application/json"
#-d '{
#    "amount": 2000,
#    "currency": "USD",
#    "source": "tok_visa", // Use a valid token for real tests
#    "description": "Test charge"
#}'
POST http://localhost:9012/api/stripe/charge
Content-Type: application/json

{
  "amount": 2000,
  "currency": "USD",
  "source": "tok_visa",
  "description": "Test charge"
}

### AliPay
# curl -X POST http://localhost:8081/api/alipay/transaction
#-H "Content-Type: application/json"
#-d '{
#    "amount": "10.00",
#    "currency": "USD",
#    "otherDetails": "value"
#}'
POST http://localhost:9013/api/alipay/transaction
Content-Type: application/json

{
  "amount": "10.00",
  "currency": "USD",
  "otherDetails": "value"
}


### PayPal Create Payment by SalesOrder
POST http://localhost:9011/api/v1/payments/paypal/create
Content-Type: application/json

{
  "salesOrderSn": "ORDER001",
  "customerId": 1,
  "supplierId": 1,
  "customerName": "John Doe",
  "customerEmail": "johndoe@example.com",
  "orderDate": "2024-01-11T15:30:45",
  "totalAmount": 1500.00,
  "shippingAddress": "123 Main St, Anytown, AT 12345",
  "billingAddress": "456 Secondary St, Othertown, OT 67890",
  "orderStatus": "PENDING",
  "paymentMethod": "PayPal",
  "paymentProcessed": false,
  "lastUpdated": "2024-01-11T10:00:00",
  "expirationDate": "2024-02-11T10:00:00"
}

### Complete PayPal Payment
POST http://localhost:9011/api/v1/payments/paypal/complete
Content-Type: application/x-www-form-urlencoded

paymentId=PAYID-MWQNGGI6BW25967JP786114D&PayerID=ExamplePayerID&SupplierId=1



