server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umi_paymen_test
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      platform: mysql

  thymeleaf:
    cache: false
  application:
    name: PAYMENT-PAYPAL-SERVICE

# host url for prod env
prod-backend: https://v2.quickmall24.com
prod-frontend: https://www.quickmall24.com
# host url for local dev
local-backend: http://localhost:9001
local-frontend: http://localhost:3000
local-auth-backend: https://3a6c-66-253-183-231.ngrok-free.app

paypal:
  client:
    id: AWhLD4_pmHlrCpHJSSKobJ4nwbwy_e16mcgbtrL_M5DzBaJk9zj84QYazMoy5TB7htSmjry7_ArOE9yU
    secret: EGVLVd0YufvNfz8ID2uN_mGRubofoTt2oZNy7CaYLGx2vHPCryZ5PuIve7LpLXxKQ7tDClvFePHBS7lN
  mode: 'sandbox'
  redirect:
    uri: ${local-auth-backend}/api/v1/suppliers/v2/callback # ${local-auth-backend}  # ${prod-backend}
  frontend:
    base:
      uri: ${local-frontend} # ${local-frontend}  # ${prod-frontend}
    redirect:
      uri: ${local-frontend}/supplier-ims/ # ${local-frontend}  # ${prod-frontend}
  referral:
    uri: ${local-backend}/api/v1/suppliers/refer # ${local-backend} # ${prod-backend}

info:
  app:
    name: PAYMENT-PAYPAL-SERVICE
    description: This is PAYMENT-PAYPAL-SERVICE
    version: 1.0.0
management:
  endpoint:
    web:
      exposure:
        include:
          info, health